<a href="https://colab.research.google.com/github/aviral911/DataScienceAndVisualization/blob/main/web.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import numpy as np
import matplotlib as plt

In [ ]:

sdf=pd.read_csv("/content/student_data_100_rows (6).txt",sep="\t")

In [ ]:
sdf.head()

,student_id,name,age,gender,department,year,attendance_percent,marks,study_hours_per_day,grade
0,STU001,Yash Singh,18,Other,ECE,2,65.0,82.9,5.6,B
1,STU002,Akash Mehta,18,Other,Mechanical,1,56.3,49.2,4.3,D
2,STU003,Aarav Mehta,19,Other,IT,4,64.9,73.3,6.6,B
3,STU004,Aarav Patel,23,Female,ECE,3,62.0,97.2,3.0,A
4,STU005,Arjun Saxena,18,Female,ECE,3,91.3,82.4,4.5,B

In [ ]:
# excel file
df2= pd.read_excel("/content/studentsttttttttttt.xlsx")

In [ ]:
df2.head()

,student_id,name,department,semester,attendance_pct,study_hours_per_week,assignment_score,exam_score,learning_preference,grade
0,1001,Asha,CSE,3,92,12,88,86,Video,B
1,1002,Ravi,CSE,4,78,7,72,70,Quiz,C
2,1003,Imran,IT,3,85,9,81,79,Forum,C
3,1004,Neha,CSE,5,96,14,95,94,Video,A
4,1005,Karan,IT,4,67,5,61,58,Hints,F

In [ ]:

data = {
    "Name": ["Aviral", "Rahul", "Priya", "Aman", "Neha"],
    "Age": [20, 21, 19, 22, 20],
    "Course": ["CSE", "IT", "AIML", "CSE", "DS"],
    "Marks": [85, 78, 92, 74, 88]
}

df1 = pd.DataFrame(data)

print(df1)

     Name  Age Course  Marks
0  Aviral   20    CSE     85
1   Rahul   21     IT     78
2   Priya   19   AIML     92
3    Aman   22    CSE     74
4    Neha   20     DS     88

In [ ]:
df1.to_csv("data2",)

In [ ]:
team = {
    "team_name": "Royal Challengers Bengaluru",
    "captain": "Rajat Patidar",
    "trophy_wins": 1,
    "players": ["Virat Kohli", "Phil Salt", "Bhuvneshwar Kumar"],
    "is_champion": True
}

print(team)

In [28]:
team = {
    "team_name": "Royal Challengers Bengaluru",
    "captain": "Rajat Patidar",
    "trophy_wins": 1,
    "players": ["Virat Kohli", "Phil Salt", "Bhuvneshwar Kumar"]
}
df.to_pickle("data.pkl")